name: infoBAG
title: infoBAG
incremental: true

permalink: "/:slug/"

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-data
  - jekyll-mermaid
  
sass:
  sass_dir: _sass
  style: :compressed

git_log: false

markdown: kramdown
kramdown:
  input: GFM

liquid:
  error_mode: strict
