name:                Intentionally Blank
title:               Intentionally Blank
url:                 https://ib.bsb.br/
enforce_ssl:         ib.bsb.br
baseurl:             ""
include:             ['_pages']
exclude:             
author:              sonny

permalink:           /blog/:slug
relative_permalinks: false

plugins:
  - jekyll-redirect-from
  - jekyll-last-modified-at

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  notes:
    output: true
    permalink: /notes/:path
  bookshelf:
    output: true
    permalink: /bookshelf/:path

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_bookshelf/**/*.md"
    values:
      layout: "bookshelf"
