repository: marioseixas/marioseixas.github.io
name: infoBAG
title: infoBAG
url: https://ib.bsb.br
enforce_ssl: ib.bsb.br
baseurl: ""

permalink: "/:slug/"
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-readme-index

sass:
  sass_dir: _sass
  style: :compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default

  - scope:
      path: "tags"
    values:
      layout: tags

  - scope:
      path: "tag"
    values:
      layout: tag

collections:
  tags:
    output: true

menu:
  home: "/"
  tags: "/tags/"

git_log: false

markdown: kramdown
kramdown:
  input: GFM
