repository: marioseixas/marioseixas.github.io
name: infoBAG
title: infoBAG
url: https://ib.bsb.br
enforce_ssl: ib.bsb.br
baseurl: ""

permalink: "/:slug/"
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-data
  - jekyll-mermaid

sass:
  sass_dir: _sass
  style: :compressed

defaults:
  - scope:
      path: ""
    values:
      layout: null

git_log: false

markdown: kramdown
kramdown:
  input: GFM

mermaid:
  src: 'https://cdn.jsdelivr.net/npm/mermaid@10.9.1/dist/mermaid.esm.min.mjs'

liquid:
  error_mode: strict
