title: infoBAG
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
    permalink: /:slug/
  uploads:
    title: Uploads
    output: true

defaults:
  - scope:
      path: "**/*"
    values:
      layout: default

repository: marioseixas/marioseixas.github.io
name: infoBAG
url: https://ib.bsb.br
enforce_ssl: ib.bsb.br
baseurl: ''

permalink: "/:slug/"

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: :compressed

menu:
  home: "/"
  tags: "/tags/"

git_log: false
