name:                Intentionally Blank
title:               Intentionally Blank
url:                 https://ib.bsb.br/
enforce_ssl:         ib.bsb.br
baseurl:             ""

permalink:           /:slug
relative_permalinks: false

plugins:
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-feed

sass:
  sass_dir:          _sass
  style:            :compressed

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
