repository: marioseixas/marioseixas.github.io
name: infoBAG
title: infoBAG
url: https://ib.bsb.br
enforce_ssl: ib.bsb.br
baseurl: ""

permalink: "/:slug/"
relative_permalinks: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-readme-index

sass:
  sass_dir: _sass
  style: :compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default

menu:
  home: "/"

git_log: false

markdown: kramdown
kramdown:
  input: GFM

# Custom settings for fetching and converting .ics file
calendar:
  url: "https://dav.heydola.com/dav.php/calendars/py28wj81/default/?export"
  username: "py28wj81"
  password: "20287290"
