---
title: infoBAG
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: "**/*"
  values:
    layout: default
repository: marioseixas/marioseixas.github.io
name: infoBAG
url: https://ib.bsb.br
enforce_ssl: ib.bsb.br
baseurl: ''
relative_permalinks: true
plugins:
- jekyll-redirect-from
- jekyll-last-modified-at
- jekyll-sitemap
- jekyll-feed
sass:
  sass_dir: _sass
  style: :compressed
menu:
  home: "/"
  tags: "/tags/"
git_log: false
