name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python script.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add assets/data/events.json
          git commit -m "Update events.json" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true

      - name: Install Ruby dependencies
        run: bundle install

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        env:
          PAGES_REPO_NWO: marioseixas/marioseixas.github.io
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
          echo "Generated site size: $(du -sh _site | cut -f1)"
        
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install PageFind
        run: npm install -g pagefind

      - name: Run PageFind indexing
        run: npx -y pagefind --site _site --output-subdir _site/pagefind

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
