name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true        

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pyyaml
          fi

      - name: Cache tag data
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.jekyll-cache
          key: tag-data-${{ github.sha }}
          save-always: true
          restore-keys: |
            tag-data-

      - name: Process markdown files for tags
        run: python tags.py

      - name: Cache Jekyll _site directory
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/_site
          key: jekyll-site-${{ github.sha }}
          save-always: true
          restore-keys: |
            jekyll-site-

      - name: Fetch calendar events
        run: python events.py

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -f assets/data/events.json _data/processed_tags.yml _includes/tag_graph.html _data/processed_tags.json
          git commit --allow-empty -m "Update events.json, processed_tags.yml, tag_graph.html, processed_tags.json" || echo "Nothing to commit"
          git push origin main || echo "Nothing to push"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        env:
          PAGES_REPO_NWO: marioseixas/marioseixas.github.io
          JEKYLL_ENV: production
          base_path: /
        run: |
          echo "base_path from env is: ${base_path}"
          export base_path="${base_path}" 
          echo "base_path after export is: ${base_path}"          
          bundle exec jekyll build --trace --verbose --config _config.yml

      - name: Generate Pagefind Index
        run: |
          npx -y pagefind --site ${{ github.workspace }}/_site --output-path ${{ github.workspace }}/_site/pagefind

      - name: Modify Pagefind UI
        run: python modify-pagefind-ui.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/_site
          publish_branch: gh-pages
          cname: ib.bsb.br
          allow_empty_commit: true
          enable_jekyll: true
